# Generated by Django 4.2.1 on 2023-07-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0019_alter_boleta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='usuario',
        ),
    ]
